export const GET_ALL_HOUSES = "GET_ALL_HOUSES"
export const GET_HOUSE = "GET_HOUSE"
export const CREATE_HOUSE = "CREATE_HOUSE"
export const ADD_HOUSE = "ADD_HOUSE"
export const CLEAR_HOUSE = "CLEAR_HOUSE"