export const GET_ALL_HOUSES = "GET_ALL_HOUSES"
export const GET_HOUSE = "GET_HOUSE"
export const CREATE_HOUSE = "CREATE_HOUSE"
export const DELETE_HOUSE = "DELETE_HOUSE"
export const ADD_HOUSE = "ADD_HOUSE"